package com.atuinfo.common.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class Base诊疗频率项目<M extends Base诊疗频率项目<M>> extends Model<M> implements IBean {

	public void set编码(String 编码) {
		set("编码", 编码);
	}

	public String get编码() {
		return getStr("编码");
	}

	public void set名称(String 名称) {
		set("名称", 名称);
	}

	public String get名称() {
		return getStr("名称");
	}

	public void set简码(String 简码) {
		set("简码", 简码);
	}

	public String get简码() {
		return getStr("简码");
	}

	public void set英文名称(String 英文名称) {
		set("英文名称", 英文名称);
	}

	public String get英文名称() {
		return getStr("英文名称");
	}

	public void set频率次数(Integer 频率次数) {
		set("频率次数", 频率次数);
	}

	public Integer get频率次数() {
		return getInt("频率次数");
	}

	public void set频率间隔(Integer 频率间隔) {
		set("频率间隔", 频率间隔);
	}

	public Integer get频率间隔() {
		return getInt("频率间隔");
	}

	public void set间隔单位(String 间隔单位) {
		set("间隔单位", 间隔单位);
	}

	public String get间隔单位() {
		return getStr("间隔单位");
	}

	public void set适用范围(Integer 适用范围) {
		set("适用范围", 适用范围);
	}

	public Integer get适用范围() {
		return getInt("适用范围");
	}

}
