package com.atuinfo.common.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class Base病人医嘱记录<M extends Base病人医嘱记录<M>> extends Model<M> implements IBean {

	public void setId(Long id) {
		set("ID", id);
	}

	public Long getId() {
		return getLong("ID");
	}

	public void set相关id(Long 相关id) {
		set("相关ID", 相关id);
	}

	public Long get相关id() {
		return getLong("相关ID");
	}

	public void set前提id(Long 前提id) {
		set("前提ID", 前提id);
	}

	public Long get前提id() {
		return getLong("前提ID");
	}

	public void set病人来源(Integer 病人来源) {
		set("病人来源", 病人来源);
	}

	public Integer get病人来源() {
		return getInt("病人来源");
	}

	public void set病人id(Long 病人id) {
		set("病人ID", 病人id);
	}

	public Long get病人id() {
		return getLong("病人ID");
	}

	public void set主页id(Integer 主页id) {
		set("主页ID", 主页id);
	}

	public Integer get主页id() {
		return getInt("主页ID");
	}

	public void set挂号单(String 挂号单) {
		set("挂号单", 挂号单);
	}

	public String get挂号单() {
		return getStr("挂号单");
	}

	public void set婴儿(Integer 婴儿) {
		set("婴儿", 婴儿);
	}

	public Integer get婴儿() {
		return getInt("婴儿");
	}

	public void set姓名(String 姓名) {
		set("姓名", 姓名);
	}

	public String get姓名() {
		return getStr("姓名");
	}

	public void set性别(String 性别) {
		set("性别", 性别);
	}

	public String get性别() {
		return getStr("性别");
	}

	public void set年龄(String 年龄) {
		set("年龄", 年龄);
	}

	public String get年龄() {
		return getStr("年龄");
	}

	public void set病人科室id(Long 病人科室id) {
		set("病人科室ID", 病人科室id);
	}

	public Long get病人科室id() {
		return getLong("病人科室ID");
	}

	public void set序号(Long 序号) {
		set("序号", 序号);
	}

	public Long get序号() {
		return getLong("序号");
	}

	public void set医嘱状态(Integer 医嘱状态) {
		set("医嘱状态", 医嘱状态);
	}

	public Integer get医嘱状态() {
		return getInt("医嘱状态");
	}

	public void set医嘱期效(Integer 医嘱期效) {
		set("医嘱期效", 医嘱期效);
	}

	public Integer get医嘱期效() {
		return getInt("医嘱期效");
	}

	public void set诊疗类别(String 诊疗类别) {
		set("诊疗类别", 诊疗类别);
	}

	public String get诊疗类别() {
		return getStr("诊疗类别");
	}

	public void set诊疗项目id(Long 诊疗项目id) {
		set("诊疗项目ID", 诊疗项目id);
	}

	public Long get诊疗项目id() {
		return getLong("诊疗项目ID");
	}

	public void set标本部位(String 标本部位) {
		set("标本部位", 标本部位);
	}

	public String get标本部位() {
		return getStr("标本部位");
	}

	public void set检查方法(String 检查方法) {
		set("检查方法", 检查方法);
	}

	public String get检查方法() {
		return getStr("检查方法");
	}

	public void set收费细目id(Long 收费细目id) {
		set("收费细目ID", 收费细目id);
	}

	public Long get收费细目id() {
		return getLong("收费细目ID");
	}

	public void set天数(java.math.BigDecimal 天数) {
		set("天数", 天数);
	}

	public java.math.BigDecimal get天数() {
		return get("天数");
	}

	public void set单次用量(java.math.BigDecimal 单次用量) {
		set("单次用量", 单次用量);
	}

	public java.math.BigDecimal get单次用量() {
		return get("单次用量");
	}

	public void set首次用量(java.math.BigDecimal 首次用量) {
		set("首次用量", 首次用量);
	}

	public java.math.BigDecimal get首次用量() {
		return get("首次用量");
	}

	public void set总给予量(java.math.BigDecimal 总给予量) {
		set("总给予量", 总给予量);
	}

	public java.math.BigDecimal get总给予量() {
		return get("总给予量");
	}

	public void set医嘱内容(String 医嘱内容) {
		set("医嘱内容", 医嘱内容);
	}

	public String get医嘱内容() {
		return getStr("医嘱内容");
	}

	public void set医生嘱托(String 医生嘱托) {
		set("医生嘱托", 医生嘱托);
	}

	public String get医生嘱托() {
		return getStr("医生嘱托");
	}

	public void set执行科室id(Long 执行科室id) {
		set("执行科室ID", 执行科室id);
	}

	public Long get执行科室id() {
		return getLong("执行科室ID");
	}

	public void set皮试结果(String 皮试结果) {
		set("皮试结果", 皮试结果);
	}

	public String get皮试结果() {
		return getStr("皮试结果");
	}

	public void set执行频次(String 执行频次) {
		set("执行频次", 执行频次);
	}

	public String get执行频次() {
		return getStr("执行频次");
	}

	public void set频率次数(Integer 频率次数) {
		set("频率次数", 频率次数);
	}

	public Integer get频率次数() {
		return getInt("频率次数");
	}

	public void set频率间隔(Integer 频率间隔) {
		set("频率间隔", 频率间隔);
	}

	public Integer get频率间隔() {
		return getInt("频率间隔");
	}

	public void set间隔单位(String 间隔单位) {
		set("间隔单位", 间隔单位);
	}

	public String get间隔单位() {
		return getStr("间隔单位");
	}

	public void set执行时间方案(String 执行时间方案) {
		set("执行时间方案", 执行时间方案);
	}

	public String get执行时间方案() {
		return getStr("执行时间方案");
	}

	public void set计价特性(Integer 计价特性) {
		set("计价特性", 计价特性);
	}

	public Integer get计价特性() {
		return getInt("计价特性");
	}

	public void set执行性质(Integer 执行性质) {
		set("执行性质", 执行性质);
	}

	public Integer get执行性质() {
		return getInt("执行性质");
	}

	public void set执行标记(Integer 执行标记) {
		set("执行标记", 执行标记);
	}

	public Integer get执行标记() {
		return getInt("执行标记");
	}

	public void set审核标记(Integer 审核标记) {
		set("审核标记", 审核标记);
	}

	public Integer get审核标记() {
		return getInt("审核标记");
	}

	public void set可否分零(Integer 可否分零) {
		set("可否分零", 可否分零);
	}

	public Integer get可否分零() {
		return getInt("可否分零");
	}

	public void set紧急标志(Integer 紧急标志) {
		set("紧急标志", 紧急标志);
	}

	public Integer get紧急标志() {
		return getInt("紧急标志");
	}

	public void set开始执行时间(java.util.Date 开始执行时间) {
		set("开始执行时间", 开始执行时间);
	}

	public java.util.Date get开始执行时间() {
		return get("开始执行时间");
	}

	public void set执行终止时间(java.util.Date 执行终止时间) {
		set("执行终止时间", 执行终止时间);
	}

	public java.util.Date get执行终止时间() {
		return get("执行终止时间");
	}

	public void set上次执行时间(java.util.Date 上次执行时间) {
		set("上次执行时间", 上次执行时间);
	}

	public java.util.Date get上次执行时间() {
		return get("上次执行时间");
	}

	public void set上次打印时间(java.util.Date 上次打印时间) {
		set("上次打印时间", 上次打印时间);
	}

	public java.util.Date get上次打印时间() {
		return get("上次打印时间");
	}

	public void set开嘱科室id(Long 开嘱科室id) {
		set("开嘱科室ID", 开嘱科室id);
	}

	public Long get开嘱科室id() {
		return getLong("开嘱科室ID");
	}

	public void set开嘱医生(String 开嘱医生) {
		set("开嘱医生", 开嘱医生);
	}

	public String get开嘱医生() {
		return getStr("开嘱医生");
	}

	public void set开嘱时间(java.util.Date 开嘱时间) {
		set("开嘱时间", 开嘱时间);
	}

	public java.util.Date get开嘱时间() {
		return get("开嘱时间");
	}

	public void set校对护士(String 校对护士) {
		set("校对护士", 校对护士);
	}

	public String get校对护士() {
		return getStr("校对护士");
	}

	public void set校对时间(java.util.Date 校对时间) {
		set("校对时间", 校对时间);
	}

	public java.util.Date get校对时间() {
		return get("校对时间");
	}

	public void set停嘱医生(String 停嘱医生) {
		set("停嘱医生", 停嘱医生);
	}

	public String get停嘱医生() {
		return getStr("停嘱医生");
	}

	public void set停嘱时间(java.util.Date 停嘱时间) {
		set("停嘱时间", 停嘱时间);
	}

	public java.util.Date get停嘱时间() {
		return get("停嘱时间");
	}

	public void set确认停嘱时间(java.util.Date 确认停嘱时间) {
		set("确认停嘱时间", 确认停嘱时间);
	}

	public java.util.Date get确认停嘱时间() {
		return get("确认停嘱时间");
	}

	public void set确认停嘱护士(String 确认停嘱护士) {
		set("确认停嘱护士", 确认停嘱护士);
	}

	public String get确认停嘱护士() {
		return getStr("确认停嘱护士");
	}

	public void set手术时间(java.util.Date 手术时间) {
		set("手术时间", 手术时间);
	}

	public java.util.Date get手术时间() {
		return get("手术时间");
	}

	public void set是否上传(Integer 是否上传) {
		set("是否上传", 是否上传);
	}

	public Integer get是否上传() {
		return getInt("是否上传");
	}

	public void set审查结果(Integer 审查结果) {
		set("审查结果", 审查结果);
	}

	public Integer get审查结果() {
		return getInt("审查结果");
	}

	public void set屏蔽打印(Integer 屏蔽打印) {
		set("屏蔽打印", 屏蔽打印);
	}

	public Integer get屏蔽打印() {
		return getInt("屏蔽打印");
	}

	public void set摘要(String 摘要) {
		set("摘要", 摘要);
	}

	public String get摘要() {
		return getStr("摘要");
	}

	public void set零费记帐(Integer 零费记帐) {
		set("零费记帐", 零费记帐);
	}

	public Integer get零费记帐() {
		return getInt("零费记帐");
	}

	public void set用药目的(Integer 用药目的) {
		set("用药目的", 用药目的);
	}

	public Integer get用药目的() {
		return getInt("用药目的");
	}

	public void set用药理由(String 用药理由) {
		set("用药理由", 用药理由);
	}

	public String get用药理由() {
		return getStr("用药理由");
	}

	public void set审核状态(Integer 审核状态) {
		set("审核状态", 审核状态);
	}

	public Integer get审核状态() {
		return getInt("审核状态");
	}

	public void set申请序号(Long 申请序号) {
		set("申请序号", 申请序号);
	}

	public Long get申请序号() {
		return getLong("申请序号");
	}

	public void set超量说明(String 超量说明) {
		set("超量说明", 超量说明);
	}

	public String get超量说明() {
		return getStr("超量说明");
	}

	public void set是否费用审核(Integer 是否费用审核) {
		set("是否费用审核", 是否费用审核);
	}

	public Integer get是否费用审核() {
		return getInt("是否费用审核");
	}

	public void set配方id(Long 配方id) {
		set("配方ID", 配方id);
	}

	public Long get配方id() {
		return getLong("配方ID");
	}

	public void set手术情况(Integer 手术情况) {
		set("手术情况", 手术情况);
	}

	public Integer get手术情况() {
		return getInt("手术情况");
	}

	public void set组合项目id(Long 组合项目id) {
		set("组合项目ID", 组合项目id);
	}

	public Long get组合项目id() {
		return getLong("组合项目ID");
	}

	public void set重整标志(Integer 重整标志) {
		set("重整标志", 重整标志);
	}

	public Integer get重整标志() {
		return getInt("重整标志");
	}

	public void set新开签名id(Long 新开签名id) {
		set("新开签名ID", 新开签名id);
	}

	public Long get新开签名id() {
		return getLong("新开签名ID");
	}

	public void set待转出(Integer 待转出) {
		set("待转出", 待转出);
	}

	public Integer get待转出() {
		return getInt("待转出");
	}

	public void set药师审核标志(Integer 药师审核标志) {
		set("药师审核标志", 药师审核标志);
	}

	public Integer get药师审核标志() {
		return getInt("药师审核标志");
	}

	public void set药师审核时间(java.util.Date 药师审核时间) {
		set("药师审核时间", 药师审核时间);
	}

	public java.util.Date get药师审核时间() {
		return get("药师审核时间");
	}

	public void set药师审核原因(String 药师审核原因) {
		set("药师审核原因", 药师审核原因);
	}

	public String get药师审核原因() {
		return getStr("药师审核原因");
	}

	public void set禁忌药品说明(String 禁忌药品说明) {
		set("禁忌药品说明", 禁忌药品说明);
	}

	public String get禁忌药品说明() {
		return getStr("禁忌药品说明");
	}

}
