package com.atuinfo.common.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class Base诊疗项目类别<M extends Base诊疗项目类别<M>> extends Model<M> implements IBean {

	public void set编码(String 编码) {
		set("编码", 编码);
	}

	public String get编码() {
		return getStr("编码");
	}

	public void set名称(String 名称) {
		set("名称", 名称);
	}

	public String get名称() {
		return getStr("名称");
	}

	public void set简码(String 简码) {
		set("简码", 简码);
	}

	public String get简码() {
		return getStr("简码");
	}

}
